### ISSUE TITLE
Abstract picks up anchor from figure

### ISSUE THREAD

**Issue by martinthomson** [miekg/mmark#101]
See https://raw.githubusercontent.com/martinthomson/4572bis/df95c1552c12e143bbb9ff105b5afd90690a2a63/draft-jennings-4572bis.md

The second figure in the document includes a caption with an anchor: `{#abnf}`

This seems to produce the right XML, but the abstract picks up the same anchor attribute and that's not valid, so xml2rfc complains.

**Comment by miekg** [comment]
Is it possible to make the `.md` smaller and that is still has this behavior?
Right now if you reference `#abnf` you get `abstract`?

**Comment by martinthomson** [comment]
I get anchors on both the figure AND the abstract, so referencing `#abnf` just doesn't work.

Sorry about the example, not much time to play around. Wasted what I had trying to understand your code to no avail. I will try to reduce, figured that something was better than nothing.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] Abstract picks up..." ]
>I get anchors on both the figure AND the abstract, so referencing `#abnf` just doesn't work.
>
>Sorry about the example, not much time to play around. Wasted what I had trying to understand your code to no avail. I will try to reduce, figured that something was better than nothing.

That would be appreciated.

Thanks

**Comment by miekg** [comment]
So I looked a bit, but you can't actually use references like this in mmark (yes known bug, would be nice if you could etc. etc.). You'll need to specify the ref *before* the figure:
~~~
    {#abnf}
    ```
    figure
    ```
~~~
Also `{#abstract}` has no effect in xml2rfc version2, you still can't reference the abstract.

**Comment by martinthomson** [comment]
Awesome.  I have updated your wiki with details.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] Abstract picks up..." ]
>Awesome.  I have updated your wiki with details.

nice! thank you.
