### ISSUE TITLE
{{ include }} always fails with "no such file or directory"

### ISSUE THREAD

**Issue by kerryland** [miekg/mmark#102]
Given two files:

*index.mmark*:
```
{{ include-this.mmark }}
```
and *include-this.mmark*:
```
 -- this should be included --
```
When I run mmark it dies:
```
2017/01/09 14:55:08 mmark: failed: ` include-this.mmark ': open  include-this.mmark : no such file or directory
```
... rather than generating a new file containing the "included" content. I get the same problem if I use an absolute path to "include-this.mmark".

Note that I am actually trying to use mmark via hugo, and [originally described the problem](https://discuss.gohugo.io/t/how-to-share-md-content/4835/4) in their forum.

Is this a bug, or am I just missing something?

**Comment by travisbaker** [comment]
I am experiencing the same issue.

**Comment by miekg** [comment]
you should either use absolute paths or run mmark in the dir where these files are (yes, that a bug). The includes work relative to mmark's *cwd*, not the location of the file

**Comment by kerryland** [comment]
I _was_ running mmark in the directory where the files are:

    ls -l *.mmark
    -rw-rw-r-- 1 kerry kerry 31 Jan  9 14:54 include-this.mmark
    -rw-rw-r-- 1 kerry kerry 27 Jan  9 14:55 _index.mmark
    mmark _index.mmark out.mmark
    2017/01/11 07:26:27 mmark: failed: ` include-this.mmark ': open  include-this.mmark : no such file or directory

also, using absolute paths does not help:

    echo '{{ /tmp/include-this.mmark }}' > proof.mmark
    echo 'hello world' > /tmp/include-this.mmark
    mmark proof.mmark out.mmark
    2017/01/11 07:28:04 mmark: failed: ` /tmp/include-this.mmark ': open  /tmp/include-this.mmark : no such file or directory

**Comment by kerryland** [comment]
PS: mmark -version gives "1.3+", on Ubuntu 16.04.1 LTS

**Comment by kerryland** [comment]
Also, FYI, instructions for building mmark seem quite broken (I am not a "go" developer).

I needed to ```go get github.com/BurntSushi/toml``` to stop ```go build``` from generating an error, but once successfully run nothing obvious happened. Certainly there is no "mmark" binary to run. Spying a makefile I randomly ran "make" in the root directory, but it failed with:
````
( cd mmark; make)
make[1]: Entering directory '/home/kerry/apps/mmark/mmark/mmark'
go build -ldflags "-X main.githash=2d4f1dd" -a -tags netgo -installsuffix netgo
main.go:21:2: cannot find package "github.com/miekg/mmark" in any of:
        /usr/lib/go-1.6/src/github.com/miekg/mmark (from $GOROOT)
        /home/kerry/.go/src/github.com/miekg/mmark (from $GOPATH)
Makefile:6: recipe for target 'mmark' failed
make[1]: *** [mmark] Error 1
make[1]: Leaving directory '/home/kerry/apps/mmark/mmark/mmark'
Makefile:4: recipe for target 'mmark/mmark' failed
make: *** [mmark/mmark] Error 2
````
That said, I'd be happier to just use a released binary :-)

**Comment by miekg** [comment]
What's the smallest text that exibits this error?

**Comment by kerryland** [comment]
````
echo '{{ /tmp/include-this.mmark }}' > proof.mmark
echo 'hello world' > /tmp/include-this.mmark
mmark proof.mmark out.mmark
````

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] {{ include }} alw..." ]
>````
>echo '{{ /tmp/include-this.mmark }}' > proof.mmark
>echo 'hello world' > /tmp/include-this.mmark
>mmark proof.mmark out.mmark
>````

2017/01/11 08:01:32 mmark: failed: ` /tmp/include-this.mmark ': open  /tmp/include-this.mmark : no such file or directory

Ah, there is a space.. Hmm `{{/tmp/include-this.mmark}}` should work.

Looking through the syntax https://github.com/miekg/mmark/wiki/Syntax doc you
can't use spaces here.

**Comment by kerryland** [comment]
Thank you. I should've spotted that myself given the error message. That said, it does seem a little silly.

**Comment by miekg** [comment]
yeah, stripping whitespace left and right seems an easy fix. Not sure why I never implemented that, maybe I had good reasons at the time

**Comment by miekg** [comment]
I think it might be that `{{ ..... }}` might be used in normal text, and the one without spaces is less likely.... IIRC

**Comment by kerryland** [comment]
That may be true, but if I was to use ```{{ here is some text }}```, with spaces, in normal text it will still fail with a "no such file or directory" error, so the whitespace doesn't help :-)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] {{ include }} alw..." ]
>That may be true, but if I was to use ```{{ here is some text }}```, with spaces, in normal text it will still fail with a "no such file or directory" error, so the whitespace doesn't help :-)

Good point.

**Comment by marksou** [comment]
I too am having this issue with Hugo. I have no whitespace in the link. I'm using v0.27.1 of Hugo, which now supports mmark (and BlackFriday) out of the box. The include file does get generated by Hugo ( I can view it directly to it from the localhost view when running hugo server). It just doesn't get displayed at the link location in the mmark file.
