### ISSUE TITLE
Set attributes for a list

### ISSUE THREAD

**Issue by cboettig** [miekg/mmark#108]
I see that `mmark` supports attribute lists. I'd like to generate a reverse ordered list: `<ol reversed="reversed">` , but cannot seem to figure out the syntax.

```
{reversed="reversed"}
1. Third
1. Second
1. First
```

seems like the suggested syntax but no luck, that just turns the list into a `<p>` and puts the attribute list as a literal (same with the attribute list at the end).  What am I missing?  Is this something that could be supported in future?  (e.g. attribute lists in kramdown work fine on ordered lists).  

Thanks for an awesome package, these really are nice extensions from blackfriday!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/mmark] Set attributes for a ..." ]
>I see that `mmark` supports attribute lists. I'd like to generate a reverse ordered list: `<ol reversed="reversed">` , but cannot seem to figure out the syntax.
>
>```
>{reversed="reversed"}
>1. Third
>1. Second
>1. First
>```
>
>seems like the suggested syntax but no luck, that just turns the list into a `<p>` and puts the attribute list as a literal (same with the attribute list at the end).  What am I missing?  Is this something that could be supported in future?  (e.g. attribute lists in kramdown work fine on ordered lists).
>
>Thanks for an awesome package, these really are nice extensions from blackfriday!

Thanks!

The HTML generated gives me:

~~~
{reversed="reversed"}
1. Third
1. Second
1. First

<ol reversed="reversed">
<li>Third</li>
<li>Second</li>
<li>First</li>
</ol>
~~~

Admittedly https://github.com/miekg/mmark/wiki/Syntax#inline-attribute-lists is
a bit terse on the subject.

/Miek

--
Miek Gieben

**Comment by mikhail73** [comment]
Is it possible to generate such attributes for a tag `<li>`?
```
<li value="72" id="72">
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] Set attributes fo..." ]
>Is it possible to generate such attributes for a tag `<li>`?
>```
><li value="72" id="72">
>```

No, when adding that I ran into problems of actually still correctly parsing the
list. Right now the IAL are silently discarded even.

The unplanned work to port mmark to blackfriday 2 (which has a sane(r) parser)
should/would fix things like these.
