### ISSUE TITLE
-css and -head parameters not working?

### ISSUE THREAD

**Issue by abh** [miekg/mmark#110]
Calling mmark like this:
```
        mmark \
           -page \
           -head ./head.html \
           index.md > index.html
```

doesn't seem to include the "head.html" bits.  What am I doing wrong?

**Comment by miekg** [comment]
Yes, you'll need a title block, just starting your doc with a `%` should be enough.

Not at all obvious. Pondering if this is a documentation bug, bug or feature.

**Comment by tsaleh** [comment]
This one got me.  Might be worth printing a warning on stderr if `-head` or `-css` are specified, but cannot be applied because of lack of `%`.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] -css and -head pa..." ]
>This one got me.  Might be worth printing a warning on stderr if `-head` or `-css` are specified, but cannot be applied because of lack of `%`.

Think the rational of not doing this by default was that little markdown 
snippets end up with an HTML header. Maybe mmark should just not care and do 
what the users wants?
