### ISSUE TITLE
I think the v1.3.5 releases for different archs are actually the same binary... 

### ISSUE THREAD

**Issue by tsaleh** [miekg/mmark#111]
same size tarballs...

![mmark 2017-07-10 10-55-06](https://user-images.githubusercontent.com/2016/28032126-4cdc8c34-655e-11e7-8a90-75bf4b9a0db4.png)

Won't exec on OS X...

```
$ ./bin/mmark
-bash: ./bin/mmark: cannot execute binary file: Exec format error
$ file bin/mmark
bin/mmark: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

And diff says they're the same...

```
$ diff -s mmark_darwin mmark_linux
Files mmark_darwin and mmark_linux are identical
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/mmark] I think the v1.3.5 re..." ]
>same size tarballs...
>
>![mmark 2017-07-10 10-55-06](https://user-images.githubusercontent.com/2016/28032126-4cdc8c34-655e-11e7-8a90-75bf4b9a0db4.png)
>
>Won't exec on OS X...
>
>```
>$ ./bin/mmark
>-bash: ./bin/mmark: cannot execute binary file: Exec format error
>$ file bin/mmark
>bin/mmark: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
>```
>
>And diff says they're the same...
>
>```
>$ diff -s mmark_darwin mmark_linux
>Files mmark_darwin and mmark_linux are identical
>```

That seems ... suboptimal. Fixed Makefile.release and pushed 1.3.6 with the 
correct architecture(s).

**Comment by tsaleh** [comment]
Looks good to me!
