### ISSUE TITLE
Can mmark generate a TOC?

### ISSUE THREAD

**Issue by tsaleh** [miekg/mmark#113]
[Kinda looks like it can](https://github.com/miekg/mmark/wiki/Syntax#pis), but I tried it and it didn't seem to work.

**Comment by miekg** [comment]
No. I ripped that out some time ago. Mostly because xml2rfc does this
itself. Consider it something that should happen in a post processing step
or in JavaScript...

**Comment by tsaleh** [comment]
Cool - I was also thinking JS might be a better solution.  Thanks!
