### ISSUE TITLE
table row/column spanning doesn't work as documented

### ISSUE THREAD

**Issue by mpounsett** [miekg/mmark#115]
The wiki syntax page says to use multiple pipe syntax for _row_ spanning, but then links to documentation on using the same syntax for _column_ spanning.   Neither seems to work as documented.

The example given:
```
Name    |Nickname  | Age
--------|----------|-----:
Bob     | The One  | 27
Alice   ||         | 23
======= |==========| ====
Charlie ||         | 4
```
Throws the following errors:
```
2017/07/20 11:58:50 mmark: syntax not supported: TableCell: colspan=2
2017/07/20 11:58:50 mmark: syntax not supported: TableCell: colspan=2
```
The example from the linked document throws similar errors.

**Comment by anthonyfok** [comment]
> The wiki syntax page says to use multiple pipe syntax for row spanning, but then links to documentation on using the same syntax for column spanning.

Good catch!  I went ahead and changed "row spanning" to "column spanning (`colspan`)" at https://github.com/miekg/mmark/wiki/Syntax.

Column spanning works fine here on mmark v1.3.6 on Debian GNU/Linux with the example:

```
Name    |Nickname  | Age
--------|----------|-----:
Bob     | The One  | 27
Alice   ||         | 23
======= |==========| ====
Charlie ||         | 4
```

producing:

```html
<table>
<thead>
<tr>
<th>Name</th>
<th>Nickname</th>
<th align="right">Age</th>
</tr>
</thead>

<tbody>
<tr>
<td>Bob</td>
<td>The One</td>
<td align="right">27</td>
</tr>

<tr>
<td colspan="2">Alice</td>
<td align="right"></td>
</tr>
</tbody>
<tfoot>
<tr>
<td colspan="2">Charlie</td>
<td align="right"></td>
</tr>
</tfoot>
</table>
```

@mpounsett, could you please share your OS environment and your mmark v1.3.6 so perhaps someone can try to reproduce the problem you're seeing and debug it?  Thank you!

**Comment by anthonyfok** [comment]
@mpounsett, were you trying to generate "xml2rfc v2", i.e. were you using `mmark -xml2`?

I did more with the latest release, i.e., mmark v1.3.6, and no errors for the default HTML output as well as xml2rfc **v3** output (`-xml`).  But with `-xml2`, the error appears.

Reading Issue #29, it would appear that colspan and rowspan were not supported in "xml2rfc v2"?
In that case, mmark isn't buggy here, maybe except that it does not yet support `rowspan` (known issue).

See also Issue #95

**Comment by mpounsett** [comment]
Probably?  That was a year ago and I don't remember what document triggered me to file the bug.  I suppose if the feature is xml2rfc v3 specific then the mmark feature should probably be marked as only useful with -xml3.

Thanks for tracking that down.
