### ISSUE TITLE
Noting an Internet-Draft on using Markdown to write RFCs

### ISSUE THREAD

**Issue by vielmetti** [miekg/mmark#12]
Noted here

https://datatracker.ietf.org/doc/draft-ietf-appsawg-text-markdown-use-cases/
https://datatracker.ietf.org/doc/draft-ietf-appsawg-text-markdown/

I didn't see an explicit reference to `mmark` there, and it would be worthwhile to ensure that this project is properly represented there.

**Comment by miekg** [comment]
Some time ago I review an earlier version of that doc (there was only one at the time) and AFIACT that entire doc just says:
`text/markdown` is markdown and then goes of the rails describing what it could be.

You think mmark markdown is a thing now? I'm not sure if I consider the format stable enough (yet)

**Comment by vielmetti** [comment]
I reread the draft - all things considered it would probably be a better use of time to work on #9 (better docs) and create some examples. perhaps to re-code some historical RFCs in `mmark` to show use. I'll comment further there.
