### ISSUE TITLE
Includes inside a code block

### ISSUE THREAD

**Issue by autarch** [miekg/mmark#124]
It would be really nice to be able to include a file inside a fenced code block, like this:

`````
```perl
{{path/to/File.pm}}
```
`````

Unfortunately, the include is rendered as-is because the code block is not parsed for any sort of additional markup content.

I'm not sure what the best fix is. Plenty of languages use constructs like `{foo}` so blindly parsing these blocks is not a good idea. Maybe a better idea would be a way to specify formatting of the include, something like this:

    {{path/to/File.pm}}(lang="perl")

?

**Comment by miekg** [comment]
<{{path/to/File.pm}} include the file *as* a code block, I think that is what you want.
