### ISSUE TITLE
Multiple definitions or paragraph in definition list doesn't work with xml2

### ISSUE THREAD

**Issue by stanford-scs** [miekg/mmark#125]
The mmark documentation contains the following example:

~~~~
Mmark
: A Markdown-superset converter

: A project on Github

Black Friday
:     Another Markdown-superset converter
~~~~

However, this doesn't work in xml2 mode.  I get this where the two definitions are run together:

~~~~
$ mmark -xml2 -page test.md
...
<t>
<list style="hanging">
<t hangText="Mmark">
<vspace />
A Markdown-superset converterA project on Github</t>
...
~~~~

What's worse, I can't find any way to generate a paragraph or line break inside a definition list.  However, xml3 mode (via the `-xml` option) seems to work okay, but there's no parser for that as far as I can tell.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/mmark] Multiple definitions ..." ]
>The mmark documentation contains the following example:
>
>~~~~
>Mmark
>: A Markdown-superset converter
>
>: A project on Github
>
>Black Friday
>:     Another Markdown-superset converter
>~~~~
>
>However, this doesn't work in xml2 mode.  I get this where the two definitions are run together:
>
>~~~~
>$ mmark -xml2 -page test.md
>...
><t>
><list style="hanging">
><t hangText="Mmark">
><vspace />
>A Markdown-superset converterA project on Github</t>
>...
>~~~~
>
>What's worse, I can't find any way to generate a paragraph or line break inside a definition list.  However, xml3 mode (via the `-xml` option) seems to work okay, but there's no parser for that as far as I can tell.

Yeah *may* get around this by inserting a html comment.
