### ISSUE TITLE
making HtmlRendererWithParameters private changes the blackfriday API

### ISSUE THREAD

**Issue by SvenDowideit** [miekg/mmark#13]
and thus causes https://github.com/spf13/hugo to fail to build :)

hugo is planning on adding vendoring, but for now, I'm building with https://github.com/miekg/mmark/commit/0ac57b30fb3721e8138e8a229856416302c5df7b removed.

```
sven@DESKTOP-Q9P9MVC /c/go/src/github.com/spf13/hugo ((v0.14))
$ go build -o hugo main.go
# github.com/spf13/hugo/helpers
helpers\content.go:208: undefined: mmark.HtmlRendererWithParameters
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[mmark] makeing HtmlRendererWithPar..." ]
>and thus causes https://github.com/spf13/hugo to fail to build :)
>
>hugo is planning on adding vendoring, but for now, I'm building with https://github.com/miekg/mmark/commit/0ac57b30fb3721e8138e8a229856416302c5df7b removed.
>
>```
>sven@DESKTOP-Q9P9MVC /c/go/src/github.com/spf13/hugo ((v0.14))
>$ go build -o hugo main.go
># github.com/spf13/hugo/helpers
>helpers\content.go:208: undefined: mmark.HtmlRendererWithParameters
>```

Ah :( Users trump devs, let me revert this. See b1ac1bc.

/Miek

--
Miek Gieben

**Comment by SvenDowideit** [comment]
ya, its a cruel world :)
