### ISSUE TITLE
Treatment of "&" in front matter

### ISSUE THREAD

**Issue by vielmetti** [miekg/mmark#21]
The current "rfc2100.md" contains this line

```
% organization = "Ashworth & Associates"
```

which generates the following XML

```
<organization>Ashworth & Associates</organization>
```

which is arguably wrong, as the ampersand character should be turned into 

```
&amp;
```
Both `tidy -xml` and `xml2rfc 2.5.0` complain.

I don't know, however, if it's the case that the markdown file needs to be changed, or if the mmark parser needs to be changed.

Noted from #8 and pulled out as a separate issue.

**Comment by miekg** [comment]
Note this is currently fixed for organizations: https://github.com/miekg/mmark/blob/master/xml2rfc.go#L142

but should be done for the other fields as well.
