### ISSUE TITLE
Use relative paths for includes

### ISSUE THREAD

**Issue by egonelbre** [miekg/mmark#36]
When organizing something bigger or per chapter it's useful to separate files by chapter. For example

```
toc.md
chapter1/toc.md
chapter1/A.md
chapter1/B.md
```

Where `toc.md` contains:

```
# Chapter 1
{{chapter1/toc.md}}
```

and  `chapter1/toc.md`:

```
## A
{{A.md}}

## B
{{B.md}}
```

Here `mmark toc.md` complains about missing `A.md` and `B.md`. Similarly, when you run `mmark` outside of the folder it isn't able to find them. (`mmark chapter1/toc.md > index.html`)

I suspect that something similar would happen with code includes.

Also, I think it might be worthwhile to standardize the includes to use paths with forward slashes and add appropriate corrections before `ioutil.ReadFile`. This would ensure that the documents will be buildable on both Windows and Unix.

Since this would introduce a context or a filename that would be needed to thread through many places, I'm bit apprehensive making this fix myself -- although I certainly could try it. Aand... there are multiple ways of implementing it, i.e. introduce a interface that can be used to load files (something like `http.FileSystem`), access disk directly or something inbetween.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[mmark] Use relative paths for incl..." ]
>When organizing something bigger or per chapter it's useful to separate files by chapter. For example
>
>```
>toc.md
>chapter1/toc.md
>chapter1/A.md
>chapter1/B.md
>```
>
>Where `toc.md` contains:
>
>```
># Chapter 1
>{{chapter1/toc.md}}
>```
>
>and  `chapter1/toc.md`:
>
>```
>## A
>{{A.md}}
>
>## B
>{{B.md}}
>```
>
>Here `mmark toc.md` complains about missing `A.md` and `B.md`. Similarly, when you run `mmark` outside of the folder it isn't able to find them. (`mmark chapter1/toc.md > index.html`)
>
>I suspect that something similar would happen with code includes.

Yep, this is all relative to where you run `mmark` from, unless the file starts
with a /

>Also, I think it might be worthwhile to standardize the includes to use paths with forward slashes and add appropriate corrections before `ioutil.ReadFile`. This would ensure that the documents will be buildable on both Windows and Unix.

Good point.

>Since this would introduce a context or a filename that would be needed to thread through many places, I'm bit apprehensive making this fix myself -- although I certainly could try it. Aand... there are multiple ways of implementing it, i.e. introduce a interface that can be used to load files (something like `http.FileSystem`), access disk directly or something inbetween.

an interface is usually a nice way of solving this, but this is mostly just
normalizing a filename for use. Please go ahead and create a PR.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
`ioutil.ReadFile` is only used twice in the code... having this be a method on `*parser` and keeping track of the `cwd` of a file when doing the includes seems like a simple approach. That with `filepath.FromSlash` and it is almost there.

**Comment by egonelbre** [comment]
One of the reasons I would be leaning towards the interface approach, is that it would allow nicer testing. e.g. easily define a whole filesystem:

```
fs := vfs{
	"toc.md": `{{chapter1/toc.md}}`,
	"chapter1/toc.md": `{{A.md}}`,
	"chapter1/A.md": `A`,
}
```

But, sure the `cwd` approach would be definitely easier.

**Comment by miekg** [comment]
That's true. I'm fine with an interface as well.

**Comment by egonelbre** [comment]
After doing the first stage of adding the interface I realized, it might be more problematic. The code blocks are included in the second-pass, whereas the regular includes are included in the first-pass. During the second pass the current working directory is lost, but is still needed for the correct code-block including.

I wouldn't want to introduce an inconsistency either i.e. regular import vs. code-import; it would be worse than it is currently.

I currently cannot see an easy solution to this. The sanest way seems to do `codeInclude` during `firstPass` and letting the `secondPass` handle the figures and callouts as usual for the regular code blocks.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mmark] Use relative paths for ..." ]
>After doing the first stage of adding the interface I realized, it might be more problematic. The code blocks are included in the second-pass, whereas the regular includes are included in the first-pass. During the second pass the current working directory is lost, but is still needed for the correct code-block including.
>
>I wouldn't want to introduce an inconsistency either i.e. regular import vs. code-import; it would be worse than it is currently.
>
>I currently cannot see an easy solution to this. The sanest way seems to do `codeInclude` during `firstPass` and letting the `secondPass` handle the figures and callouts as usual for the regular code blocks.

Ack, also note issue #6 which (I think) means code includes should move the
first-pass anyway. But this has down sides as well. As codeblock includes are
allowed in lists (and as such don't start at the beginning of the line).

/Miek

--
Miek Gieben

**Comment by egonelbre** [comment]
Seems that I got the block inclusion working properly, but one questions remains. How should I introduce the "current working directory" to the public API. Currently `mmark.Parse` takes the content as input. Most reasonable would be to add `mmark.ParseAt` or `mmark.ParseInDir` to avoid breaking API (not sure about the best name though).

Also, I cannot run the RFC tests, to see whether I broke them, I guess this can wait until I change to relative paths. The standard tests seem to run fine.

**Comment by egonelbre** [comment]
Anyways, I made one version, that I thought would be best... just let me know what pieces need to be fixed or changed. PS: Since I cannot easily test the RFC folder (running on Windows), could you please verify that it works as intended.
