### ISSUE TITLE
The Abbreviations does not work in the Hugo

### ISSUE THREAD

**Issue by mikhail73** [miekg/mmark#60]
This is a bug, or it is specifically disabled? The BlackFriday has ability to customize modules in the Hugo. Is it possible to customize modules of the mmark in the Hugo?

**Comment by miekg** [comment]
I don't know... maybe this topic is better suited for the hugo forums.

**Comment by anthonyfok** [comment]
Thanks for reporting this, @mikhail73.  Indeed, the trouble lies with my previous incomplete work on mmark support in Hugo, so it is Hugo's code that needs to be worked on to match mmark's features.  Please see spf13/hugo#1970 for further discussion and development on this Hugo issue.  Thanks!

@miekg, thank you for redirecting @mikhail73 to our discussion forum.  Please feel free to close this Issue #60.  :-)

Cheers,
Anthony

**Comment by anthonyfok** [comment]
Sorry, I forgot to provide the link to @mikhail73's post on the Hugo forum.  Here it is (for completeness sake):

https://discuss.gohugo.io/t/the-abbreviations-mmark-does-not-work-in-the-hugo/2867

**Comment by miekg** [comment]
thanks for the help!
