### ISSUE TITLE
Algorithm rendering of footnotes

### ISSUE THREAD

**Issue by mikhail73** [miekg/mmark#64]
As we know, when rendering the list empty lines added the p tag.

```
- bla-bla => <li>bla-bla</li>
- bla-bla => <li>bla-bla</li>
```
 empty lines added the p tag:
```
- bla-bla => <li><p>bla-bla</p></li>

- bla-bla => <li><p>bla-bla</p></li>
```
It seems to me that it would be logical to render footnotes on the same algorithm. By adding the  p tag instead of empty lines.

```
[^1]: bla-bla => <li>bla-bla</li>
[^2]: bla-bla => <li>bla-bla</li>
```
 empty lines added the p tag:

```
[^1]: bla-bla => <li><p>bla-bla</p></li>

[^2]: bla-bla => <li><p>bla-bla</p></li>
```

Now the p tag is only added for multiline footnotes, and as a result, multiline footnote have vertical margins greater than other list items.

```
[^1]: bla-bla => <li>bla-bla</li>

[^2]: bla-bla => <li><p>bla-bla</p>
    
    bla-bla  => <p>bla-bla</p></li>

[^3]: bla-bla => <li>bla-bla</li>
```

**Comment by miekg** [comment]
Suggest filing this with black friday, as said in #65, I'll backport the fix
