### ISSUE TITLE
Footnote at the end of the line.

### ISSUE THREAD

**Issue by mikhail73** [miekg/mmark#65]
BlackFriday and mmark strange generates a footnote at the end of the line. It looks like bug.

Hugo 0.15, Windows 7 (utf-8)
```
bla-bla[^1]

[^1]: bla-bla.
```
Generates:

`<p>bla-bla<sup class="footnote-ref" id="fnref:f12e258d46bb8c2f10e42d0148b09a6e:1"><a class="footnote" href="#fn:f12e258d46bb8c2f10e42d0148b09a6e:1">1</a></sup></p>`

But:

```
bla-bla[^1] bla-bla.

[^1]: bla-bla.
```

Generates:

`<p>bla-bla<sup class="footnote-ref" id="fnref:1"><a class="footnote" href="#fn:1">1</a></sup> bla-bla.</p>`

**Comment by miekg** [comment]
If this is also an issue with blackfriday, it's best to fill it there. I'll then try to merge their fix back into mmark.
