### ISSUE TITLE
Include part of file, not as code block?

### ISSUE THREAD

**Issue by breschke** [miekg/mmark#66]
I would like to include part of another mmark file--skipping the TOML. I get very close with the code excerpt syntax (e.g., <{{path/to/file.mmark}[12,]) but rather than represent line 12 onward as a code block, I'd like this markdown to be rendered along with the 'parent' mmark file. Is this possible?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[mmark] Include part of file, not a..." ]
>I would like to include part of another mmark file--skipping the TOML. I get very close with the code excerpt syntax (e.g., <{{path/to/file.mmark}[12,]) but rather than represent line 12 onward as a code block, I'd like this markdown to be rendered along with the 'parent' mmark file. Is this possible?

Good bug, no this is not possible as the markdown include syntax does not
support the addressing the code-include has.

We should add that.


/Miek

--
Miek Gieben
