### ISSUE TITLE
Internet Drafts and version numbers 

### ISSUE THREAD

**Issue by ogud** [miekg/mmark#7]
Miek, 

xmlrfc.ietf.org has XML file for every version of drafts but the anchor in all versions is the same 
example: file http://xml2rfc.ietf.org/public/rfc/bibxml3/reference.I-D.draft-ietf-dane-openpgpkey-03.xml
see: reference anchor="I-D.ietf-dane-openpgpkey"
and that is true for -02 as well 
If I write in markup file [@?I-D.ietf-dane-openpgpkey]
I get an error in xmlrfc that the file does not exist. 
Because: 
<?rfc include="http://xml.resource.org/public/rfc/bibxml3/reference.I-D.draft-i\
etf-dane-openpgpkey.xml"?>
After I edit the resulting file to have the reference fetch to include version number things work. 
Suggested fix 
If the [@?I.D.... ] contains a version number strip that from xref but include in file name fetched.

Olafur

**Comment by miekg** [comment]
Note that you can specificy the number with `#<NUM>` in the ref.
```
 [@?I-D.ietf-dane-openpgpkey#02]
```
for instance.

But it may be nice to have it default to the latest version. I'll ask xml2rfc.ietf.org to make a non-versioned anchor that points to the latests draft. (In general that looks like a nice thing to have)

**Comment by miekg** [comment]
Counter argument could be that you should always default to a specific version of a draft. *Another* solution would be to default to version `-00` if non is provided.

**Comment by miekg** [comment]
They already do this except the url is different:

reference.I-D.draft-foo-bar-##.xml                                                               
and                                                                                              
reference.I-D.foo-bar.xml  - for the latest.

**Comment by miekg** [comment]
should be fixed in the latest master.
