### ISSUE TITLE
Can't access website

### ISSUE THREAD

**Issue by oblitum** [miekg/mmark#70]
I can't access https://miek.nl/tags/mmark to check the spec, I've got this:

```
An error occurred during a connection to miek.nl. Invalid OCSP signing certificate in OCSP response. 
Error code: SEC_ERROR_OCSP_INVALID_SIGNING_CERT
```

Thanks for this, I love this markdown flavor.

**Comment by oblitum** [comment]
I just now need a Vim syntax file....

**Comment by oblitum** [comment]
I can't access it prefixing with www.

**Comment by oblitum** [comment]
Sorry, I meant I can access.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/mmark] Can't access website ..." ]
>I can't access https://miek.nl/tags/mmark to check the spec, I've got this:
>
>```
>An error occurred during a connection to miek.nl. Invalid OCSP signing certificate in OCSP response. Error code: SEC_ERROR_OCSP_INVALID_SIGNING_CERT
>```

I see, firefox throws this error for me as well... :(

**Comment by oblitum** [comment]
Working now.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] Can't access webs..." ]
>Working now.

dunno what that was, only firefox had problems. Restarted the webserver.

Thanks for the ping!


/Miek

--
Miek Gieben
