### ISSUE TITLE
Issues w/ example lists

### ISSUE THREAD

**Issue by Dieterbe** [miekg/mmark#72]
Hi, this looks like an interesting project.
I decided to try out a few things I saw on https://github.com/miekg/mmark/wiki/Syntax 
and ran into two issues.
i used the latest code, installed like so:
```
$ go get -u github.com/miekg/mmark/mmark
$ mmark -version
1.3.2
```

```
$ cat spec.md
 % title = "My Awesome Title"


Mmark
: A Markdown-superset converter

Black Friday
: Another Markdown-superset converter



 * [foo](http://bar)
 * [foo](http://bar)
 * [foo](http://bar)
 * [foo](http://bar)
 * [foo](http://bar)
 * [foo](http://bar)
 * [foo](http://bar)
 * [foo](http://bar)


(@good)  This is a good example.

As (@good) illustrates

(@good)  Another example.

As (@good) also illustrates

Name    | Age
--------|-----:
Bob     | 27
Alice   | 23

|-----------------+------------+-----------------+----------------|
| Default aligned |Left aligned| Center aligned  | Right aligned  |
|-----------------|:-----------|:---------------:|---------------:|
| First body part |Second cell | Third cell      | fourth cell    |
| Second line     |foo         | **strong**      | baz            |
| Third line      |quux        | baz             | bar            |
|-----------------+------------+-----------------+----------------|
| Second body     |            |                 |                |
| 2 line          |            |                 |                |
|=================+============+=================+================|
| Footer row      |            |                 |                |
|-----------------+------------+-----------------+----------------|


This is a footnote.[^1]

[^1]: the footnote text.

$ mmark spec.md test.html
2016/05/05 22:05:11 mmark: handling `@good' as normal text
```

the first issue is the definitions are rendered like:
```
<dl>
<dt>Mmark</dt><dd>A Markdown-superset converter</dd>
<dt>Black Friday</dt>
<dd><p>Another Markdown-superset converter</p>
```
why is the second one in a new paragraph?

and the example lists render like so:
```
This is a good example.

As (@good) illustrates

Another example.
As (1) also illustrates
```

why ?
thanks.

**Comment by Dieterbe** [comment]
also i just noticed the title just renders as `% title = "My Awesome Title"`

i also tried running the command as `mmark -page spec.md test.html` instead but all 3 issues remain.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] trying it with, r..." ]
>also i just noticed the title just renders as `% title = "My Awesome Title"`

The title block generation only works for XML output. Main problem is that I
don't now what to output for the authors element.... The `title` it self is not
hard, but the other elements are. Ideas in this regard are welcome.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
> the first issue is the definitions are rendered like:
>
> 
> ~~~
> <dl>
> <dt>Mmark</dt><dd>A Markdown-superset converter</dd>
> <dt>Black Friday</dt>
> <dd><p>Another Markdown-superset converter</p>
> ~~~
That because the `<dl>` is ony closed after "This is a good example." because that is the first non-indented test seen.

The example list thing is not good, the first use of `(@good)` should have been detected but isn't

**Comment by miekg** [comment]
ok, the example list is seen as being part of the `* [foo](http://bar)` list, which is obviously not what you'd expect. Ties into these issues a bit: https://github.com/miekg/mmark/pull/71 and https://github.com/russross/blackfriday/pull/261.

I'll file this as an new issue.

**Comment by miekg** [comment]
https://github.com/miekg/mmark/issues/73

**Comment by miekg** [comment]
And see PR #74 which fixes the example list thing.

**Comment by Dieterbe** [comment]
> Main problem is that I don't now what to output for the authors element.... The `title` it self is not hard, but the other elements are. Ideas in this regard are welcome.

you could maybe just render as a list like:
```
<h1>Title</h1>
<ul>
<li>author: your name</li>
<li>category: whatever</li>
</ul>
```
or in a table, so that things are nicely aligned. 
I don't really care much, I do think that rendering things like `% title = "My Awesome Title"` looks quite bad and `<h1>My awesome title</h1>` would be much better.

any idea on how to solve the definition list problem? 
the output looks like so:
```
<dl>
<dt>Mmark</dt><dd>A Markdown-superset converter</dd>
<dt>Black Friday</dt>
<dd><p>Another Markdown-superset converter</p>

<ul>
<li><a href="http://bar">foo</a></li>
<li><a href="http://bar">foo</a></li>
<li><a href="http://bar">foo</a></li>
<li><a href="http://bar">foo</a></li>
<li><a href="http://bar">foo</a></li>
<li><a href="http://bar">foo</a></li>
<li><a href="http://bar">foo</a></li>
<li><a href="http://bar">foo</a></li>
</ul></dd>
</dl>

```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] Issues w/ example..." ]
>you could maybe just render as a list like:
>```
><h1>Title</h1>
><ul>
><li>author: your name</li>
><li>category: whatever</li>
></ul>
>```
>or in a table, so that things are nicely aligned.

Yes, but it's meta data so you don't wont to output in the document as-is. Now
people need it filter it out if they don't wont it. Was more eyeing meta-tags
are something.... Appreciate the idea though.

>I don't really care much, I do think that rendering things like `% title = "My Awesome Title"` looks quite bad and `<h1>My awesome title</h1>` would be much better.

When do you see this?

>any idea on how to solve the definition list problem?
>the output looks like so:
>```
><dl>
><dt>Mmark</dt><dd>A Markdown-superset converter</dd>
><dt>Black Friday</dt>
><dd><p>Another Markdown-superset converter</p>
>
><ul>
><li><a href="http://bar">foo</a></li>
><li><a href="http://bar">foo</a></li>
><li><a href="http://bar">foo</a></li>
><li><a href="http://bar">foo</a></li>
><li><a href="http://bar">foo</a></li>
><li><a href="http://bar">foo</a></li>
><li><a href="http://bar">foo</a></li>
><li><a href="http://bar">foo</a></li>
></ul></dd>
></dl>
>```

Ah, I see even *without* the initial space this belong to the initial `dl`

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
So #76 fixes the rest, if there is a initial space, the content is considered part of the definition list, is not it is a new list.

**Comment by miekg** [comment]
Merged all the PR on the issues you raised. Thanks for those!

Added #78 on the titleblock output in HTML5.

Think of closing this one as #78 is the only remaining one?

**Comment by Dieterbe** [comment]
Sure. Thanks
