### ISSUE TITLE
integration test

### ISSUE THREAD

**Issue by miekg** [miekg/mmark#8]
Should do a full test, build a draft and compile it to text and then compare it to some previous test. Might be harder than it sounds, especially when xml2rfc changes.

**Comment by vielmetti** [comment]
what's your favorite test environment? I've used `bats` recently and it's relatively straightforward, every test is a shell command so the setup is minimal.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mmark] integration test (#8)..." ]
>what's your favorite test environment? I've used `bats` recently and it's relatively straightforward, every test is a shell command so the setup is minimal.

Don't use any, just `go test`, but integrating that with xml2rfc is of course
harder.

grtz Miek

**Comment by vielmetti** [comment]
You had mentioned varieties of versions of `xml2rfc`. If we set up Travis right, we can test against several of them (definitely the latest from `pip`, plus whatever others are useful).

I see `xml2rfc` available via pip at https://pypi.python.org/pypi/xml2rfc . It means bootstrapping the Travis config to install both go and python, and I'm sure someone has done that before.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mmark] integration test (#8)..." ]
>You had mentioned varieties of versions of `xml2rfc`. If we set up Travis right, we can test against several of them (definitely the latest from `pip`, plus whatever others are useful).
>
>I see `xml2rfc` available via pip at https://pypi.python.org/pypi/xml2rfc . It means bootstrapping the Travis config to install both go and python, and I'm sure someone has done that before.

I do the same-ish thing for SkyDNS, download and use etcd. So this approach will
work. I doubt if *anyone* in the world has done this for xml2rfc though...

But the tests become pretty easy, compare each input against a version output
files, input.md -> intput.txt and compare that with output-xml2rfc-2.4.8.txt
or something like that.

/Miek

--
Miek Gieben

**Comment by vielmetti** [comment]
I queried at https://github.com/travis-ci/travis-ci/issues/4090 (the multiple language support question) to look for best examples to work from. The matrix gets pretty big pretty fast.

If no one has done it before, we should expect to find some bugs.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mmark] integration test (#8)..." ]
>I queried at https://github.com/travis-ci/travis-ci/issues/4090 (the multiple language support question) to look for best examples to work from. The matrix gets pretty big pretty fast.
>
>If no one has done it before, we should expect to find some bugs.

Ah, I see what you mean.

/Miek

--
Miek Gieben

**Comment by vielmetti** [comment]
So I have a build environment in travis that includes python and xml2rfc from the IETF, which wasn't too difficult in Travis. I haven't yet tried to set up lots of versions of python, that can come much later.

I pinged the IETF test server and it reports an xml2rfc version of 2.5.1.dev0, but that version is not yet available from `pip`:

> Collecting xml2rfc==2.5.1.dev0
>  Could not find a version that satisfies the requirement xml2rfc==2.5.1.dev0 (from versions: 2.2.7, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 2.3.11, 2.3.11.1, 2.3.11.2, 2.3.11.3, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.4.10.dev0, 2.4.10, 2.4.11, 2.4.12, 2.5.0)

I don't think it's sane to try to test against every one of these releases just yet, but I picked 2.4.12 and 2.5.0 as likely ones to build against. 

I'm also bringing in the `bats` test tool, so I'll stop here for now and think about doing the very smallest shell script test that proves that something might possibly work with xml2rfc, and then go on from there.

**Comment by vielmetti** [comment]
See https://github.com/miekg/mmark/pull/20 for a stab at this.

It does 

>  build a draft and compile it to text 

and does not yet do 

> and then compare it to some previous test.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mmark] integration test (#8)..." ]
>So I have a build environment in travis that includes python and xml2rfc from the IETF, which wasn't too difficult in Travis. I haven't yet tried to set up lots of versions of python, that can come much later.
>
>I pinged the IETF test server and it reports an xml2rfc version of 2.5.1.dev0, but that version is not yet available from `pip`:
>
>> Collecting xml2rfc==2.5.1.dev0
>>  Could not find a version that satisfies the requirement xml2rfc==2.5.1.dev0 (from versions: 2.2.7, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 2.3.11, 2.3.11.1, 2.3.11.2, 2.3.11.3, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.4.10.dev0, 2.4.10, 2.4.11, 2.4.12, 2.5.0)
>
>I don't think it's sane to try to test against every one of these releases just yet, but I picked 2.4.12 and 2.5.0 as likely ones to build against.

Ack, that's fine.

>I'm also bringing in the `bats` test tool, so I'll stop here for now and think about doing the very smallest shell script test that proves that something might possibly work with xml2rfc, and then go on from there.

Sound good.

Thanks!

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
Might not actually need xml2rfc v2 (the python thing) just validate against the DTD from https://tools.ietf.org/html/draft-iab-xml2rfcv2-02 with xmllint

**Comment by miekg** [comment]
mmark2 has better testing
