### ISSUE TITLE
Bibtex Citations

### ISSUE THREAD

**Issue by wbthomason** [miekg/mmark#88]
Is there interest in permitting Bibtex for citations (rather than just XML references)? Perhaps using something like https://github.com/nickng/bibtex? If there is, I'd be glad to add the functionality myself.

This may be a stupid question, but I've read through what seem to be the relevant parts of the source and it looks like only XML references are supported at this time.

**Comment by miekg** [comment]
you're right in that only XML refs are supported at this moment.

I think this makes perfect sense. Right now people are prolly converting this by hand.

**Comment by wbthomason** [comment]
I'm new to Go, but I'll try to throw together a PR incorporating the aforementioned library.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] Bibtex Citations ..." ]
>I'm new to Go, but I'll try to throw together a PR incorporating the
>aforementioned library.

cool, be sure to add tests and the update [synax 
doc](https://github.com/miekg/mmark/wiki/Syntax) (or send a patch for that)

Thanks!

**Comment by rachtsingh** [comment]
Hey @wbthomason any chance you got a chance to try this? I'm also interested in it :) (and trying to convert bibtex -> XML by hand). Also, it would be great to generate a references section once references are used.

My use case is writing short expository blog posts that have too little content to be a paper, but are useful to others.

**Comment by wbthomason** [comment]
Terribly sorry, but I did not! Fairly soon after this, I made a solution for my use case using a pandoc-citeproc preprocessing step and a custom template in Hugo, and completely forgot to get back to learning Go/adding this feature to `mmark`. Sorry for accidentally bailing on my offer!

**Comment by rachtsingh** [comment]
No worries! Totally understand. I might take a shot at this sometime, but no guarantees either.
