### ISSUE TITLE
better docs

### ISSUE THREAD

**Issue by miekg** [miekg/mmark#9]
Create some better docs? QuickStart? Or something.

More short example RFCs?

**Comment by vielmetti** [comment]
RFC 1149 (the first Avian Carriers RFC) might be a good first target, from April 1, 1990. It's very short, and it doesn't use all of the modern RFC features. I'll give it a try....

**Comment by vielmetti** [comment]
OK, the first try is at 

https://github.com/vielmetti/mmark/blob/master/rfc1149.md

it was pretty quick, but I'm sure I didn't get the TOML front matter correct yet.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mmark] better docs (#9)..." ]
>OK, the first try is at
>
>https://github.com/vielmetti/mmark/blob/master/rfc1149.md
>
>it was pretty quick, but I'm sure I didn't get the TOML front matter correct yet.

Yes, nice. Although that RFC is *really* simple :-) One problem with using
an RFC *that* old is that the current xml2rfc render this completely different
and it missing an abstract for instance.

This looking through the April first RFC (nice idea of using those), seems
http://www.faqs.org/rfcs/rfc5841.html is a good mix between text, figures and
references.

http://www.faqs.org/rfcs/rfc3514.html is also a good candidate.

And yes, the TOML header is severely underdocumented. I'll try to work on that.

Maybe we can add an rfc/ subdir with a couple of examples?

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mmark] better docs (#9)..." ]
>RFC 1149 (the first Avian Carriers RFC) might be a good first target, from April 1, 1990. It's very short, and it doesn't use all of the modern RFC features. I'll give it a try....

See the examples branch.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
I found this such a good idea that I've gone ahead and merged the examples branch with an example RFC. Feel free to open PRs to add more.

**Comment by miekg** [comment]
@vielmetti I cherrypicked your 1149 in the main repo. Thanks!

Made only a few modifications.

**Comment by miekg** [comment]
Closing. Added bunch of example doc, each had a special quirk.
