### ISSUE TITLE
Installation instructions may want to mention dependency on toml

### ISSUE THREAD

**Issue by danyork** [miekg/mmark#91]
Miek,
I just cloned this repo to my Mac. Since I didn't have the Go language installed, I had to download/install that and then restart my terminal window (for the path changes).  However, when I went into the mmark directory and typed `go build`, I got this error message:

```
toml.go:7:2: cannot find package "github.com/BurntSushi/toml" in any of:
    /usr/local/go/src/github.com/BurntSushi/toml (from $GOROOT)
    ($GOPATH not set)
```

I then went to https://github.com/BurntSushi/toml where I learned that what I had to do was (after setting my $GOPATH ):

```
go get github.com/BurntSushi/toml
```

Then I could go back into the mmark directory and do the build.
Anyway, for people who are brand new to using Go, you may want to note that they may need to install this other library as well.

**Comment by miekg** [comment]
Ah, yeah. Feel free to send a PR to make this better.

`go get -u` in the dir should download all deps as well, then a `go build` should just work (TM)
