### ISSUE TITLE
Couldn't install via git clone - had to do 'go get'

### ISSUE THREAD

**Issue by danyork** [miekg/mmark#92]
Miek,
Cloned the git repo to my Macbook Pro running 10.10.4.  Newly installed Go version is "go1.6.2 darwin/amd64".

After resolving issue #91, I went into the mmark subdirectory per your instructions and had this happen:

```
$ cd mmark
$ ls
Makefile    main.go     titleblock.go
$ go build
main.go:21:2: cannot find package "github.com/miekg/mmark" in any of:
    /usr/local/go/src/github.com/miekg/mmark (from $GOROOT)
    /Users/danyork/Documents/code/gocode/src/github.com/miekg/mmark (from $GOPATH)
$
```

I "solved" the issue by doing `go get github.com/miekg/mmark` and having that appear inside my $GOPATH directory.    I then had to cd over to that directory, i.e. `$GOPATH/src/github.com/miekg/mmark/mmark` and then do `go build`.

Was there a better way to do this?  Should I have set $GOPATH to the cloned directory?  (I think _not_ based on documentation I read.)

Or should installation always be via `go get github.com/miekg/mmark`?

**Comment by miekg** [comment]
`go get` is usually preferred. Mmark does nothing speciall and follows the normal rules for installling go packages.
