### ISSUE TITLE
unable to label forward refernces

### ISSUE THREAD

**Issue by dericed** [miekg/mmark#94]
In markdown, I'm written something like.

```markdown
# Introduction
This forward reference refers to a [later section]{#later-section}
# Later Section
I'd like to link to here from the introduction.
```

`mmark -xml2 -page input.md > output.xml` outputs:

```xml
<middle>

<section anchor="introduction" title="Introduction">
<t>This forward reference refers to a <xref target="later-section"/>.
</t>
</section>

<section anchor="later-section" title="Later Section">
<t>I'd like to link to here from the introduction.
</t>
</section>

</middle>
```

which `xml2rfc --html output.xml -o draft.html` renders as

```html
<h1 id="rfc.section.1"><a href="#rfc.section.1">1.</a> <a href="#introduction" id="introduction">Introduction</a></h1>
<p id="rfc.section.1.p.1">This forward reference refers to a <a href="#later-section">Section 2</a>.  </p>
<h1 id="rfc.section.2"><a href="#rfc.section.2">2.</a> <a href="#later-section" id="later-section">Later Section</a></h1>
<p id="rfc.section.2.p.1">I'd like to link to here from the introduction.  </p>
```

So in rendered HTML this reads as `This forward reference refers to a Section 2.` But I'd prefer to create my own label rather than have `Section 2` listed there. I see in the [Syntax doc](https://github.com/miekg/mmark/wiki/Syntax#headers) that Headers named after only numbers will be prefixed with `Section ` but in my case `Later Section` is not a number. How can I insert my own label on the link rather than get a numbered section?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/mmark] unable to label forwa..." ]
>which `xml2rfc --html output.xml -o draft.html` renders as
>
>```html
><h1 id="rfc.section.1"><a href="#rfc.section.1">1.</a> <a href="#introduction" id="introduction">Introduction</a></h1>
><p id="rfc.section.1.p.1">This forward reference refers to a <a href="#later-section">Section 2</a>.  </p>
><h1 id="rfc.section.2"><a href="#rfc.section.2">2.</a> <a href="#later-section" id="later-section">Later Section</a></h1>
><p id="rfc.section.2.p.1">I'd like to link to here from the introduction.  </p>
>```
>
>So in rendered HTML this reads as `This forward reference refers to a Section 2.` But I'd prefer to create my own label rather than have `Section 2` listed there. I see in the [Syntax doc](https://github.com/miekg/mmark/wiki/Syntax#headers) that Headers named after only numbers will be prefixed with `Section ` but in my case `Later Section` is not a number. How can I insert my own label on the link rather than get a numbered section?

AFAICT in *xml2rfc* XML, you can't do that. It will always insert "Section XX"
for references. Maybe this is something they are solving for v3 - but I'll have
to double check.

/Miek

--
Miek Gieben

**Comment by dericed** [comment]
OK, thanks for clarifying, I'll reword the text around the link so it reads properly.
