### ISSUE TITLE
Multiple pipe syntax doesn't seem to work

### ISSUE THREAD

**Issue by darconeous** [miekg/mmark#95]
I was trying to use the [multiple pipe syntax](http://bywordapp.com/markdown/guide.html#section-mmd-tables-colspanning) for a table, since the [documentation for mmark table syntax](https://github.com/miekg/mmark/wiki/Syntax#block-tables) indicates it is supported.

This is what my table looks like:

```
| 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
|---|---|---|---|---|---|---|---|
|  FLG ||  IID ||      TID   ||||
```

However, when I convert the document to XML, I get the following errors form mmark:

```
2016/09/06 20:57:32 mmark: syntax not supported: TableCell: colspan=2
2016/09/06 20:57:32 mmark: syntax not supported: TableCell: colspan=2
2016/09/06 20:57:32 mmark: syntax not supported: TableCell: colspan=4
```

...and the resulting text rendering looks like this:

```
+-----+-----+-----+---+---+---+---+---+
|  0  |  1  |  2  | 3 | 4 | 5 | 6 | 7 |
+-----+-----+-----+---+---+---+---+---+
| FLG | IID | TID |
+-----+-----+-----+---+---+---+---+---+
```

Is this a bug, or am I not doing it right?

**Comment by miekg** [comment]
That's should work, so I would say this is a bug

**Comment by anthonyfok** [comment]
@darconeous, were you trying to generate "xml2rfc v2", i.e. were you using `mmark -xml2`?

I was testing the latest release, i.e., mmark v1.3.6, and no errors for the default HTML output as well as xml2rfc **v3** output (`-xml`).

Reading Issue #29, it would appear that colspan and rowspan were not supported in "xml2rfc v2"?

See also Issue #115

**Comment by darconeous** [comment]
Ah-hah. I bet that was it.
