### ISSUE TITLE
Using Mmark Syntax in Hugo

### ISSUE THREAD

**Issue by nancym** [miekg/mmark#96]
I'm learning both the Mmark Syntax and Hugo, and have a suggestion for your [syntax doc](https://github.com/miekg/mmark/wiki/Syntax). I just created a `.mmark` file in my Hugo `content` directory and carefully created a title block between `%%%` lines. Hugo could not determine the title or date and I finally figured out these need to be specified like a normal Hugo `.md` file, i.e., between `+++` lines. Maybe you could add a note in the Title Block section explaining how, if at all, title blocks work in Hugo.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/mmark] Using Mmark Syntax in..." ]
>I'm learning both the Mmark Syntax and Hugo, and have a suggestion for your [syntax doc](https://github.com/miekg/mmark/wiki/Syntax). I just created a `.mmark` file in my Hugo `content` directory and carefully created a title block between `%%%` lines. Hugo could not determine the title or date and I finally figured out these need to be specified like a normal Hugo `.md` file, i.e., between `+++` lines. Maybe you could add a note in the Title Block section explaining how, if at all, title blocks work in Hugo.

I'm not aware that hugo uses mmark's titleblock for anything.... You probably
better off asking these questions on a hugo forum.

/Miek

--
Miek Gieben

**Comment by mikhail73** [comment]
@nancym In Hugo you can use the YAMAL (---) and the TOML,(+++), but you can not use MMARK (%%%). It will not work.

**Comment by nancym** [comment]
Thanks @miekg and @mikhail73. AFAICT there is no documentation at http://gohugo.io/ about using mmark. I learned about it from reading https://discuss.gohugo.io/ and following a link to https://github.com/miekg/mmark/wiki/Syntax. It's very cool that the mmark renderer is built in to Hugo and eventually I will do what I can to update the Hugo docs, but for now it seems that it would be good if the mmark Syntax doc included a note or an aside about using mmark syntax with Hugo. For example, instead of:

> A title block contain a document's meta data; title, authors, date and other elements. 

Write something like:

> A title block contains a document's meta data; title, authors, date and other elements.
>
> _**Aside:**_ If you are using mmark-flavored markdown with the Hugo website engine, you need to use [Hugo-style front-matter](https://gohugo.io/tutorials/creating-a-new-theme#front-matter) rather than an Mmark title block.

Note that I also changed "contain" to "contains".

Thanks for mmark!
