### ISSUE TITLE
uncentred figure support

### ISSUE THREAD

**Issue by mpounsett** [miekg/mmark#97]
Is it possible to include some notation that would cause figures to not be centred?  When creating a draft that contains frequent code blocks, it becomes awkward to read when the level of indent is constantly changing due to the maximum length of lines in each block.

**Comment by miekg** [comment]
Yes, you can use `{align=left}`

I should document those in https://github.com/miekg/mmark/wiki/Syntax#special-ials

**Comment by mpounsett** [comment]
That works quite well.  Thanks!
