### ISSUE TITLE
figure preamble and postamble

### ISSUE THREAD

**Issue by mpounsett** [miekg/mmark#98]
Is there (or could there be added) notation that would cause mmark to emit preamble and postamble blocks in a figure?

This has the useful benefit of causing preamble and postamble text to be tightly bound to the figure, preventing page breaks from separating them when text and HTML versions of IDs are generated.

For example:
``` xml
<figure>
   <preamble>Some text related to a figure.</preamble>
   <artwork>
bash -c 'echo "This is some code."'
   </artwork>
   <postamble>More text related to the figure.</postamble>
</figure>
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/mmark] figure preamble and p..." ]
>Is there (or could there be added) notation that would cause mmark to emit preamble and postamble blocks in a figure?

I though these were somehow deprecated, esp. in xml2rfcv3?

>This has the useful benefit of causing preamble and postamble text to be tightly bound to the figure, preventing page breaks from separating them when text and HTML versions of IDs are generated.
>
>For example:
>``` xml
><figure>
>   <preamble>Some text related to a figure.</preamble>
>   <artwork>
>bash -c 'echo "This is some code."'
>   </artwork>
>   <postamble>More text related to the figure.</postamble>
></figure>
>```

The specific question is that you want *both* a preamble and postamble?

/Miek

--
Miek Gieben

**Comment by mpounsett** [comment]
> I though these were somehow deprecated, esp. in xml2rfcv3?

I don't know about that.   I do know that I've seen them show up in new drafts.

> The specific question is that you want *both* a preamble and postamble?

Either or both.  That is, to be able to independently add a preamble or postamble, or both.

Take for example draft-ietf-dnsop-no-response-issue-05 § 9 which I'm trying to faithfully convert from xml to markdown.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] figure preamble a..." ]
>> I though these were somehow deprecated, esp. in xml2rfcv3?
>
>I don't know about that.   I do know that I've seen them show up in new drafts.

drafts. In rfcs too?

>> The specific question is that you want *both* a preamble and postamble?
>
>Either or both.  That is, to be able to independently add a preamble or postamble, or both.
>
>Take for example draft-ietf-dnsop-no-response-issue-05 § 9 which I'm trying to faithfully convert from xml to markdown.

https://tools.ietf.org/html/draft-iab-xml2rfc-04#section-3.6

I think I ripped out support for this in mmark because of that.

/Miek

--
Miek Gieben

**Comment by mpounsett** [comment]
> drafts. In rfcs too?

Given your link above ... that it's clearly deprecated ... I assume the RFC editor is removing these before publication.

I'll withdraw my feature request.  It doesn't look like this would be useful long term.

**Comment by mpounsett** [comment]
On 20 October 2016 at 12:19, Miek Gieben <notifications@github.com> wrote:

> [ Quoting <notifications@github.com> in "Re: [miekg/mmark] figure
> preamble a..." ]
> >> I though these were somehow deprecated, esp. in xml2rfcv3?
> >
> >I don't know about that. I do know that I've seen them show up in new
> drafts.
>
> drafts. In rfcs too?


I couldn't say.  But given your link below.. that it seems to be
deprecated.. I'd assume the RFC editor is removing them before publication.

I'll withdraw my feature request.  Doesn't look like this is useful long
term.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] figure preamble a..." ]
>> drafts. In rfcs too?
>
>Given your link above ... that it's clearly deprecated ... I assume the RFC editor is removing these before publication.

Yes, I vaguely remember such discussion(s) because I thought they were cool as
well :) Too lazy to dig them up, hence the link to xml2rfcv3.

/Miek

--
Miek Gieben
