### ISSUE TITLE
Problems with block tables

### ISSUE THREAD

**Issue by johndickinson** [miekg/mmark#99]
A ID containing

|-----------------+------------+-----------------+----------------|
| Default aligned |Left aligned| Center aligned  | Right aligned  |
|-----------------|:-----------|:---------------:|---------------:|
| First body part |Second cell | Third cell      | fourth cell    |
| Second line     |foo         | **strong**      | baz            |
| Third line      |quux        | baz             | bar            |
|-----------------+------------+-----------------+----------------|
| Second body     |            |                 |                |
| 2 line          |            |                 |                |
|=================+============+=================+================|
| Footer row      |            |                 |                |
|-----------------+------------+-----------------+----------------|

copied from the syntax wiki produces the following

./mmark/mmark/mmark -xml2 -page draft-dickinson-dnsop-dns-messages-00.md > x.xml && xml2rfc --text x.xml
Parsing file x.xml
ERROR: Unable to validate the XML document: x.xml
 x.xml: Line 345: Element t is not declared in c list of possible children
 x.xml: Line 349: Element t is not declared in c list of possible children
 x.xml: Line 353: Element t is not declared in c list of possible children
 x.xml: Line 357: Element t is not declared in c list of possible children
 x.xml: Line 362: Element t is not declared in c list of possible children
Rhubarb:draft jad$ go version
go version go1.7.3 darwin/amd64
Rhubarb:draft jad$ xml2rfc --version
2.5.2

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/mmark] Problems with block t..." ]
>A ID containing
>
>|-----------------+------------+-----------------+----------------|
>| Default aligned |Left aligned| Center aligned  | Right aligned  |
>|-----------------|:-----------|:---------------:|---------------:|
>| First body part |Second cell | Third cell      | fourth cell    |
>| Second line     |foo         | **strong**      | baz            |
>| Third line      |quux        | baz             | bar            |
>|-----------------+------------+-----------------+----------------|
>| Second body     |            |                 |                |
>| 2 line          |            |                 |                |
>|=================+============+=================+================|
>| Footer row      |            |                 |                |
>|-----------------+------------+-----------------+----------------|
>
>copied from the syntax wiki produces the following
>
>./mmark/mmark/mmark -xml2 -page draft-dickinson-dnsop-dns-messages-00.md > x.xml && xml2rfc --text x.xml
>Parsing file x.xml
>ERROR: Unable to validate the XML document: x.xml
> x.xml: Line 345: Element t is not declared in c list of possible children
> x.xml: Line 349: Element t is not declared in c list of possible children
> x.xml: Line 353: Element t is not declared in c list of possible children
> x.xml: Line 357: Element t is not declared in c list of possible children
> x.xml: Line 362: Element t is not declared in c list of possible children
>Rhubarb:draft jad$ go version
>go version go1.7.3 darwin/amd64
>Rhubarb:draft jad$ xml2rfc --version
>2.5.2

I don't think you can use those in xml2rfc version 2. In version 3 you should
(and that's why I added it - I think, this has been a while)

**Comment by johndickinson** [comment]
Ah ok.
Thanks
